FROM nodered/node-red-docker
RUN npm install node-red-dashboard
RUN npm install node-red-contrib-ldap-auth
RUN npm install node-red-contrib-influxdb
RUN npm install node-red-node-snmp 
RUN npm install node-red-contrib-ifttt
RUN npm install node-red-contrib-rate
RUN npm install node-red-contrib-xxtea
RUN npm install node-red-contrib-primitives
RUN npm install node-red-node-ldap

