version: '2'
    
services:
    rabbitmq:
        build: rabbitmq
        restart: unless-stopped
        hostname: rabbitmq
        volumes:
            - ./data:/var/lib/rabbitmq 
        environment:
            - RABBITMQ_DEFAULT_USER=user 
            - RABBITMQ_DEFAULT_PASS=pass
            - RABBITMQ_DEFAULT_VHOST=/
        ports:
            # AMQ
            - 5672:5672

            - 15671:15671
              # Adminweb
            - 15672:15672
              # MQTT
            - 1883:1883
            - 8883:8883
